---

- name: Set new window target ({{ finder_new_window_target }}).
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "{{ finder_new_window_target }}"
  notify: Restart Finder

- name: Show extension warning ({{ finder_show_file_extensions_warning }}).
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "{{ finder_show_file_extensions_warning|bool }}"
  notify: Restart Finder

- name: Warn before emptying the trash ({{ finder_warn_before_emptying_the_trash }}).
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: "{{ finder_warn_before_emptying_the_trash|bool }}"
  notify: Restart Finder

- name: Show All Files ({{ finder_show_all_files }})
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: "{{ finder_show_all_files|bool }}"
  notify: Restart Finder

- name: Keep folders on top when sorting by name ({{ finder_keep_folders_on_top }}).
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: "{{ finder_keep_folders_on_top|bool }}"
  notify: Restart Finder

- name: Show full path in finder titlebar ({{ finder_show_full_path_in_titlebar }}).
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: "{{ finder_show_full_path_in_titlebar|bool }}"
  notify: Restart Finder

- name: Show pathbar in bottom of finder ({{ finder_show_pathbar }}).
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "{{ finder_show_pathbar|bool }}"
  notify: Restart Finder

- name: Show statusbar ({{ finder_show_statusbar }}).
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: "{{ finder_show_statusbar|bool }}"
  notify: Restart Finder

- name: When performing a search, search the current folder by default.
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"
  notify: Restart Finder

- name: Enable quit menu item ({{ finder_enable_quit_menu_item }}).
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: "{{ finder_enable_quit_menu_item|bool }}"
  notify: Restart Finder

- name: Default view style ({{ finder_default_view_style }}).
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "{{ finder_default_view_style }}"
  notify: Restart Finder

- name: Show external harddrives on desktop ({{ finder_show_external_harddrives_on_desktop }}).
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: "{{ finder_show_external_harddrives_on_desktop|bool }}"
  notify: Restart Finder

- name: Show harddrives on desktop ({{ finder_show_harddrives_on_desktop }}).
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: "{{ finder_show_harddrives_on_desktop|bool }}"
  notify: Restart Finder

- name: Show mounted servers on desktop ({{ finder_show_mounted_servers_on_desktop }}).
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: "{{ finder_show_mounted_servers_on_desktop|bool }}"
  notify: Restart Finder

- name: Show removable media on desktop ({{ finder_show_removable_media_on_desktop }}).
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: "{{ finder_show_removable_media_on_desktop|bool }}"
  notify: Restart Finder

- name: Get user library folder status.
  shell: ls -aOl ~/Library/ | sed -n 2p
  register: user_library_folder_status
  changed_when: false

- name: Hide user library folder ({{ finder_hide_user_library }}). 
  command: "chflags {{ 'hidden' if finder_hide_user_library else 'nohidden' }} ~/Library/"
  notify: Restart Finder
  when: user_library_folder_status.stdout.find("hidden") == -1 and finder_hide_user_library or user_library_folder_status.stdout.find("hidden") != -1 and not finder_hide_user_library

- name: Get system volumes folder status.
  shell: ls -aOl /Volumes | sed -n 2p
  register: system_volumes_folder_status
  changed_when: false

- name: Hide system volumes folder ({{ finder_hide_system_volumes }}).
  command: "chflags {{ 'hidden' if finder_hide_system_volumes else 'nohidden' }} /Volumes"
  become: true
  notify: Restart Finder
  when: system_volumes_folder_status.stdout.find("hidden") == -1 and finder_hide_system_volumes or system_volumes_folder_status.stdout.find("hidden") != -1 and not finder_hide_system_volumes

- name: Get iconview show item info status.
  command: /usr/libexec/PlistBuddy -c "Print :{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "DesktopViewSettings:IconViewSettings:showItemInfo"
    - "StandardViewSettings:IconViewSettings:showItemInfo"
  register: finder_iconview_show_item_info_status
  changed_when: false

- name: Show item info near icons on the desktop and in other icon views ({{ finder_iconview_show_item_info }}).
  command: /usr/libexec/PlistBuddy -c "Set :{{ item.1.name }} {{ item.1.value }}" ~/Library/Preferences/com.apple.finder.plist
  with_indexed_items:
    - { name: "DesktopViewSettings:IconViewSettings:showItemInfo", value: "{{ finder_iconview_show_item_info | bool | string() | lower }}" }
    - { name: "StandardViewSettings:IconViewSettings:showItemInfo", value: "{{ finder_iconview_show_item_info | bool | string() | lower }}" }
  notify: Restart Finder
  when: finder_iconview_show_item_info_status.results[item.0].stdout != item.1.value

- name: Get iconview show label on bottom status.
  command: /usr/libexec/PlistBuddy -c "Print DesktopViewSettings:IconViewSettings:labelOnBottom" ~/Library/Preferences/com.apple.finder.plist
  register: finder_iconview_show_label_on_bottom_status
  changed_when: false

- name: Show item info label on the bottom of the icons on the desktop ({{ finder_iconview_show_label_on_bottom }}).
  command: /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom {{ finder_iconview_show_label_on_bottom|bool }}" ~/Library/Preferences/com.apple.finder.plist
  notify: Restart Finder
  when: finder_iconview_show_label_on_bottom_status.stdout == "false" and finder_iconview_show_label_on_bottom or finder_iconview_show_label_on_bottom_status.stdout == "true" and not finder_iconview_show_label_on_bottom

- name: Get expand settings of file info pane.
  command: /usr/libexec/PlistBuddy -c "Print :FXInfoPanesExpanded:{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - General
    - OpenWith
    - Privileges
  register: finder_expand_fileinfo_status
  changed_when: false

- name: "Expand the following File Info panes: “General”, “Open with”, and “Sharing & Permissions”."
  command: /usr/libexec/PlistBuddy -c "Set :FXInfoPanesExpanded:{{ item.1.name }} {{ item.1.value }}" ~/Library/Preferences/com.apple.finder.plist
  with_indexed_items:
    - { name: General, value: "{{ finder_expand_infopane_genenal | bool | string() | lower }}" }
    - { name: OpenWith, value: "{{ finder_expand_infopane_openwith | bool | string() | lower }}" }
    - { name: Privileges, value: "{{ finder_expand_infopane_privileges | bool | string() | lower }}" }
  notify: Restart Finder
  when: finder_expand_fileinfo_status.results[item.0].stdout != item.1.value

- name: Enable QuickLook text selection ({{ finder_enable_quicklook_text_selection }}).
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: "{{ finder_enable_quicklook_text_selection | bool }}"
  notify: Restart Finder

- name: Get iconview arrange by status.
  command: /usr/libexec/PlistBuddy -c "Print :{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "DesktopViewSettings:IconViewSettings:arrangeBy"
    - "StandardViewSettings:IconViewSettings:arrangeBy"
  register: finder_iconview_arrange_by_status
  changed_when: false

- name: Set arrange by for icons on the desktop and in other icon views ({{ finder_iconview_arrange_by }}).
  command: /usr/libexec/PlistBuddy -c "Set :{{ item.1.name }} {{ item.1.value }}" ~/Library/Preferences/com.apple.finder.plist
  with_indexed_items:
    - { name: "DesktopViewSettings:IconViewSettings:arrangeBy", value: "{{ finder_iconview_arrange_by }}" }
    - { name: "StandardViewSettings:IconViewSettings:arrangeBy", value: "{{ finder_iconview_arrange_by }}" }
  notify: Restart Finder
  when: finder_iconview_arrange_by_status.results[item.0].stdout != item.1.value

- name: Get iconview grid spacing value.
  command: /usr/libexec/PlistBuddy -c "Print :{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "DesktopViewSettings:IconViewSettings:gridSpacing"
    - "StandardViewSettings:IconViewSettings:gridSpacing"
  register: finder_iconview_grid_spacing_value
  changed_when: false

- name: Set grid spacing for icons on the desktop and in other icon views ({{ finder_iconview_grid_spacing }}).
  command: /usr/libexec/PlistBuddy -c "Set :{{ item.1.name }} {{ item.1.value }}" ~/Library/Preferences/com.apple.finder.plist
  with_indexed_items:
    - { name: "DesktopViewSettings:IconViewSettings:gridSpacing", value: "{{ \"%.6f\" | format(finder_iconview_grid_spacing|float) }}" }
    - { name: "StandardViewSettings:IconViewSettings:gridSpacing", value: "{{ \"%.6f\" | format(finder_iconview_grid_spacing|float) }}" }
  notify: Restart Finder
  when: finder_iconview_grid_spacing_value.results[item.0].stdout != item.1.value

- name: Get iconview icon size value.
  command: /usr/libexec/PlistBuddy -c "Print :{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "DesktopViewSettings:IconViewSettings:iconSize"
    - "StandardViewSettings:IconViewSettings:iconSize"
  register: finder_iconview_icon_size_value
  changed_when: false

- name: Set size of icons on the desktop and in other icon views ({{ finder_iconview_icon_size }}).
  command: /usr/libexec/PlistBuddy -c "Set :{{ item.1.name }} {{ item.1.value }}" ~/Library/Preferences/com.apple.finder.plist
  with_indexed_items:
    - { name: "DesktopViewSettings:IconViewSettings:iconSize", value: "{{ \"%.6f\" | format(finder_iconview_icon_size|float) }}" }
    - { name: "StandardViewSettings:IconViewSettings:iconSize", value: "{{ \"%.6f\" | format(finder_iconview_icon_size|float) }}" }
  notify: Restart Finder
  when: finder_iconview_icon_size_value.results[item.0].stdout != item.1.value
