---

- name: Mail - Addresses include name on pasteboard ({{ mail.address_include_name_on_pasteboard }}).
  osx_defaults:
    domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: bool
    value: "{{ mail.address_include_name_on_pasteboard | bool }}"
  notify: Restart Mail
