---

- import_tasks: system_misc.yml
  tags: [system]

- import_tasks: system_screensaver.yml
  tags: [system, screensaver]

- import_tasks: system_performance.yml
  tags: [system, performance]

- import_tasks: system_hostname.yml
  tags: [system, hostname]

- import_tasks: system_default-applications.yml
  tags: [system, default-applications]

- import_tasks: finder.yml
  tags: [finder]

- import_tasks: dock.yml
  tags: [dock]

- import_tasks: safari.yml
  tags: [safari]

- import_tasks: mail.yml
  tags: [mail]

- import_tasks: terminal.yml
  tags: [terminal] 

- import_tasks: textedit.yml
  tags: [textedit]