---

- name: Disable Dashboard ({{ system_disable_dashboard }}).
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: "{{ system_disable_dashboard | bool }}"

- name: Enable auto correct ({{ system_enable_auto_correct }}).
  osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: "{{ system_enable_auto_correct | bool }}"

- name: Enable smart quotes ({{ system_enable_smart_quotes }}).
  osx_defaults:
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: "{{ system_enable_smart_quotes | bool }}"

- name: Enable smart dashes ({{ system_enable_smart_dashes }}).
  osx_defaults:
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: "{{ system_enable_smart_dashes | bool }}"

- name: Enable automatic capitalization ({{ system_enable_automatic_capitalization }}).
  osx_defaults:
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: "{{ system_enable_automatic_capitalization | bool }}"

- name: Save application state on quit ({{ system_save_application_state_on_quit }}).
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: "{{ system_save_application_state_on_quit | bool }}"

- name: Expand save panel by default ({{ system_expand_save_panel_by_default }}).
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: "{{ system_expand_save_panel_by_default | bool }}"
  notify: Restart Finder

- name: Expand print panel by default ({{ system_expand_print_panel_by_default }}).
  osx_defaults:
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: "{{ system_expand_print_panel_by_default | bool }}"
  notify: Restart Finder

- name: Enable spring loading for directories ({{ system_enable_springloading_directories }}).
  osx_defaults:
    key: com.apple.springing.enabled
    type: bool
    value: "{{ system_enable_springloading_directories | bool }}"

- name: Set delay for spring loading directories ({{ system_springloading_directories_delay }}).
  osx_defaults:
    key: com.apple.springing.delay
    type: float
    value: "{{ system_springloading_directories_delay }}"

- name: Disable creating .DS_Store files on network shares ({{ system_disable_dsstore_on_network_shares }}).
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: "{{ system_disable_dsstore_on_network_shares | bool }}"

- name: Disable creating .DS_Store files on usb drives ({{ system_disable_dsstore_on_usb_drives }}).
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: "{{ system_disable_dsstore_on_usb_drives | bool }}"

- name: Disable disk image verification ({{ system_disable_disk_image_verification }}).
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: "{{ item }}"
    type: bool
    value: "{{ system_disable_disk_image_verification | bool }}"
  with_items:
    - skip-verify
    - skip-verify-locked
    - skip-verify-remote

- name: Set action for double click on titlebar ({{ system_doubleclick_on_titlebar_action }}).
  osx_defaults:
    key: AppleActionOnDoubleClick
    type: string
    value: "{{ system_doubleclick_on_titlebar_action }}"

- name: Set interface style ({{ system_interface_style }}).
  osx_defaults:
    key: AppleInterfaceStyle
    type: string
    value: "{{ system_interface_style }}"

- name: Enable full keyboard access for all controls ({{ system_enable_full_keyboard_access }}). #(e.g. enable Tab in modal dialogs)
  osx_defaults:
    state: "{{ 'present' if system_enable_full_keyboard_access else 'absent' }}"
    key: AppleKeyboardUIMode
    type: int
    value: 3   

- name: Enable subpixel font rendering on non-Apple LCDs ({{ system_enable_subpixel_font_rendering }}). # Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
  osx_defaults:
    state: "{{ 'present' if system_enable_subpixel_font_rendering else 'absent' }}"
    key: AppleFontSmoothing
    type: int
    value: 1 

- name: Show all file extensions ({{ system_show_all_file_extensions }}).
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: "{{ system_show_all_file_extensions | bool }}"

- name: Enable focus ring ({{ system_enable_focus_ring }}).
  osx_defaults:
    key: NSUseAnimatedFocusRing
    type: bool
    value: "{{ system_enable_focus_ring | bool }}"

- name: Set key repeat rate ({{ system_key_repeat_rate }}).
  osx_defaults:
    key: KeyRepeat
    type: int
    value: "{{ system_key_repeat_rate }}"

- name: Set initial key repeat delay ({{ system_initial_key_repeat_delay }}).
  osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: "{{ system_initial_key_repeat_delay }}"

- name: Enable press-and-hold for special characters ({{ system_enable_press_and_hold }}).
  osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: "{{ system_enable_press_and_hold | bool }}"

- name: Enable crash reporter ({{ system_enable_crash_reporter }}).
  osx_defaults:
    domain: com.apple.CrashReporter
    state: "{{ 'absent' if system_enable_crash_reporter else 'present' }}"
    key: DialogType
    type: string
    value: "none" 

- name: Get startup sound status.
  command: nvram SystemAudioVolume
  register: startup_sound_status
  become: yes
  changed_when: false
  failed_when: false

- name: Enable startup sound ({{ system_enable_startup_sound }}).
  command: "{{ 'nvram -d SystemAudioVolume' if system_enable_startup_sound else 'nvram SystemAudioVolume=\" \"' }}"
  become: yes
  when: startup_sound_status.stderr.find("Error") != -1 and not system_enable_startup_sound or startup_sound_status.stderr.find("Error") == -1 and system_enable_startup_sound

- name: Save new docs to icloud by default ({{ system_save_new_docs_to_icloud }}).
  osx_defaults:
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: "{{ system_save_new_docs_to_icloud | bool }}"

- name: Get ssh service status.
  shell: systemsetup -getremotelogin
  register: ssh_status
  changed_when: false
  become: yes

- name: Enable ssh ({{ system_enable_ssh }}).
  command: "launchctl {{ 'load -w ' if system_enable_ssh else 'unload -w' }} /System/Library/LaunchDaemons/ssh.plist"
  become: yes
  when: ssh_status.stdout.find("Off") != -1 and system_enable_ssh or ssh_status.stdout.find("On") != -1 and not system_enable_ssh

- name: Enable application quarantine ({{ system_enable_quarantine }}).
  osx_defaults:
    domain: com.apple.LaunchServices
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: "{{ system_enable_quarantine | bool }}"

#- name: Remove duplicates in the “Open With” menu.
#  command: /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local

# disable gatekeeper
#sudo -E -- /usr/sbin/spctl --master-disable
