---

- name: Screensaver - Set activation delay for screensaver ({{ system.screensaver.activation_delay }}).
  osx_defaults:
    domain: com.apple.screensaver
    host: currentHost
    key: idleTime
    type: int
    value: "{{ system.screensaver.activation_delay }}"

- name: Screensaver - Ask for a password when leaving the screensaver ({{ system.screensaver.ask_password }}).
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: "{{ system.screensaver.ask_password | int }}"

- name: Screensaver - Set ask password delay ({{ system.screensaver.ask_password_delay }}).
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: "{{ system.screensaver.ask_password_delay | float }}"
