---

- name: UI - Expand save panel by default ({{ system.ui.expand_save_panel }}).
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: "{{ system.ui.expand_save_panel | bool }}"
  notify: Restart Finder

- name: UI - Expand print panel by default ({{ system.ui.expand_print_panel }}).
  osx_defaults:
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: "{{ system.ui.expand_print_panel | bool }}"
  notify: Restart Finder

- name: UI - Enable spring loading for directories ({{ system.ui.enable_springloading_directories }}).
  osx_defaults:
    key: com.apple.springing.enabled
    type: bool
    value: "{{ system.ui.enable_springloading_directories | bool }}"

- name: UI - Set delay for spring loading directories ({{ system.ui.springloading_directories_delay }}).
  osx_defaults:
    key: com.apple.springing.delay
    type: float
    value: "{{ system.ui.springloading_directories_delay }}"

- name: UI - Set action for double click on titlebar ({{ system.ui.titlebar_doubleclick_action }}).
  osx_defaults:
    key: AppleActionOnDoubleClick
    type: string
    value: "{{ system.ui.titlebar_doubleclick_action }}"

- name: UI - Set interface style ({{ system.ui.interface_style }}).
  osx_defaults:
    key: AppleInterfaceStyle
    type: string
    value: "{{ system.ui.interface_style }}"

- name: UI - Enable subpixel font rendering on non-Apple LCDs ({{ system.ui.enable_subpixel_font_rendering }}). # Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
  osx_defaults:
    state: "{{ 'present' if system.ui.enable_subpixel_font_rendering else 'absent' }}"
    key: AppleFontSmoothing
    type: int
    value: 1 

- name: UI - Disable Dashboard ({{ system.ui.disable_dashboard }}).
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: "{{ system.ui.disable_dashboard | bool }}"

- name: UI - Show all file extensions ({{ system.ui.show_all_file_extensions }}).
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: "{{ system.ui.show_all_file_extensions | bool }}"

- name: UI - Enable focus ring ({{ system.ui.enable_focus_ring }}).
  osx_defaults:
    key: NSUseAnimatedFocusRing
    type: bool
    value: "{{ system.ui.enable_focus_ring | bool }}"

- name: UI - Enable menubar transparency ({{ system.ui.enable_menubar_transparency }}).
  osx_defaults:
    key: AppleEnableMenuBarTransparency
    type: bool
    value: "{{ system.ui.enable_menubar_transparency | bool }}"

- name: UI - Show scrollbars ({{ system.ui.show_scrollbars }}).
  osx_defaults:
    key: AppleShowScrollBars
    type: string
    value: "{{ system.ui.show_scrollbars }}"

- name: UI - Enable opening and closing window animations ({{ system.ui.enable_opening_closing_window_animations }}).
  osx_defaults:
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: "{{ system.ui.enable_opening_closing_window_animations | bool }}"

- name: UI - Set window resize speed for Cocoa applications ({{ system.ui.window_resize_speed }}).
  osx_defaults:
    key: NSWindowResizeTime
    type: float
    value: "{{ system.ui.window_resize_speed | float }}"
